# general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGS NF" }
bold = { family = "MesloLGS NF" }
italic = { family = "MesloLGS NF" }
size = 14

[font.offset]
x = 1
y = 1
[window]
# decorations = "None"
opacity = 0.9
dynamic_padding = true
padding.x = 1
padding.y = 1
[mouse]
bindings = []

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  # Disable Copy/paste mode
  { key = "Space", mods = "Control|Shift", action = "None" }
]
