words = [
    "CCNA",
    "CDP",
    "CLI",
    "Coreutils",
    "EDB",
    "Gbits",
    "IEE",
    "LACP",
    "LLDP",
    "MTU",
    "NIC",
    "RMA",
    "RSTP",
    "SFD",
    "STP",
    "SVI",
    "Sweigart",
    "Thunar",
    "Udemy",
    "VLA",
    "VLANs",
    "alacritty",
    "comptia",
    "noatime",
    "randint",
    "readlink",
    "realpath",
    "vdir",
]
