#!/usr/bin/env bash


STEP_SIZE=${STEP_SIZE:-10}
USE_SUDO=${USE_SUDO:-0}

# whether to use `sudo` for changing the brightness (requires a NOPASSWD rule)
if [[ "$USE_SUDO" == "0" ]] ; then
    LIGHT_SET="xbacklight"
else
    LIGHT_SET="sudo xbacklight"
fi

case $BLOCK_BUTTON in
  3) xset dpms force off ;; # right click
  4) $LIGHT_SET -inc "$STEP_SIZE" ;; # scroll up
  5) $LIGHT_SET -dec "$STEP_SIZE" ;; # scroll down, decrease
esac

BRIGHTNESS=$(xbacklight -get)
echo "${BRIGHTNESS%%.*}%"

