[window]
opacity = 0.85
decorations = "buttonless"
dynamic_title = true
padding = { x = 6, y = 6 }

[scrolling]
history = 10000
multiplier = 10

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[colors.normal]
black = "0x32344a"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xad8ee6"
cyan = "0x449dab"
white = "0x787c99"

[colors.bright]
black = "0x444b6a"
red = "0xff7a93"
green = "0xb9f27c"
yellow = "0xff9e64"
blue = "0x7da6ff"
magenta = "0xbb9af7"
cyan = "0x0db9d7"
white = "0xacb0d0"

[colors.cursor]
cursor = "#ECEFF4"
text = "#3B4252"

[cursor]
style = { shape = "Block", blinking = "Always" }

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[keyboard]

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

[general]
live_config_reload = true
